# Generated by Django 4.0.1 on 2022-08-16 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentName', models.CharField(max_length=50)),
                ('studentEmail', models.EmailField(max_length=100)),
                ('studentPassword', models.CharField(max_length=50)),
            ],
        ),
    ]
